const products = [
    {
        id: 0,
        name: "Harley Davidson 1200",
        description: "The mid-sized Harley-Davidson XL1200 Sportster makes a lot of sense. It's got a bit more presence, punch and space than the smaller 883cc family but without the weight and unwieldy feel of the 1340/1450cc big end motorcycles",
        category: "Harley Davidson",
        price: 39999,
        image: "./Images/HarleyDavidson1200.jpg",
        sale: true,
        saleAmount: 200,
    },
    {
        id: 1,
        name: "Harley Davidson Night Rod",
        description: "The 2016 Harley-Davidson Night Rod Special is a street-ready, blacked out, dark custom bike that’s sure to pique the interest of many riders in Anaheim and Irvine, California. It delivers all the power and performance you expect from a Harley along with a style that’s all its own.",
        category: "Harley Davidson",
        price: 79999,
        image: "./Images/harley-davidson-night-rod-03.jpg",
    },
    {
        id: 2,
        name: "Harley Davidson Softail Street Bob",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Harley Davidson",
        price: 69999,
        image: "./Images/BOB.jpg",
        sale: true,
        saleAmount: 500,
    },
    {
        id: 3,
        name: "Harley Davidson Softail Low Rider",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Harley Davidson",
        price: 99999,
        image: "./Images/Low Rider.jpg",
    },
    {
        id: 4,
        name: "Suzuki Intruder",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Suzuki",
        price: 15000,
        image: "./Images/Suzuki Intruder.jpg",
        sale: true,
        saleAmount: 800,
    },
    {
        id: 5,
        name: "Suzuki Vulcan",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Suzuki",
        price: 26999,
        image: "./Images/Vulcan.jpg",
    },
    {
        id: 6,
        name: "Suzuki Marauder",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Suzuki",
        price: 29500,
        image: "./Images/BOB.jpg",
    },
    {
        id: 7,
        name: "Indian Scout bobber",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Indian",
        price: 80500,
        image: "./Images/Indian Bober.jpg",
        sale: true,
        saleAmount: 501,
    },
    {
        id: 8,
        name: "Indian Chief",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Indian",
        price: 70800,
        image: "./Images/Chief.jpg",
    },
    {
        id: 9,
        name: "Indian Chieftain",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Indian",
        price: 29500,
        image: "./Images/Chieftain.jpg",
    },
    {
        id: 10,
        name: "Honda Shadow",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Honda",
        price: 23999,
        image: "./Images/Shadow.jpg",
        sale: true,
        saleAmount: 449, 
    
    },
    {
        id: 11,
        name: "Honda Rebel",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Honda",
        price: 11500,
        image: "./Images/Rebel.png",
    },
    {
        id: 12,
        name: "Honda NRX 1800",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Honda",
        price: 55800,
        image: "./Images/NRX.jpg",
        sale: true,
        saleAmount: 300,
    },
    {
        id: 13,
        name: "Yamaha Virago",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Yamaha",
        price: 21500,
        image: "./Images/Virago.jpg",
    },
    {
        id: 14,
        name: "Yamaha Rider",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Yamaha",
        price: 60000,
        image: "./Images/Rider.jpg",
        sale: true,
        saleAmount: 301,
    },
    {
        id: 15,
        name: "Yamaha Bolt",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Qui nulla assumenda nobis iusto distinctio praesentium ab corporis sit suscipit nihil.",
        category: "Yamaha",
        price: 44600,
        image: "./Images/Bolt.jpg",
        sale: true,
        saleAmount: 501,
    },
] 